IF NOT EXISTS
(SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Users')
BEGIN
	CREATE TABLE Users (
		UserId INT IDENTITY(1, 1),
		Username NVARCHAR(50) NOT NULL,
		PasswordHash VARCHAR(255) NOT NULL,
		Salt VARCHAR(255) NOT NULL,
		Email NVARCHAR(100) NOT NULL,
		Age INT,
		Address NVARCHAR(255),
		IsAdmin BIT NOT NULL,
		CONSTRAINT USERS_PK PRIMARY KEY(UserId),
	);

END
	CREATE NONCLUSTERED INDEX CI_UsersUsername ON Users (Username);

IF NOT EXISTS
(SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Categories')
BEGIN
	CREATE TABLE Categories (
		CategoryId INT IDENTITY(1, 1),
		CategoryName NVARCHAR(255) NOT NULL,
		CONSTRAINT CATEGORIES_PK PRIMARY KEY(CategoryId),
	);
END

IF NOT EXISTS
(SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Products')
BEGIN
	CREATE TABLE Products (
		ProductId INT IDENTITY(1, 1),
		ProductName NVARCHAR(255) NOT NULL,
		Price DECIMAL NOT NULL,
		CategoryId INT,
		CONSTRAINT PRODUCTS_PK PRIMARY KEY(ProductId),
		CONSTRAINT PRODUCTS_FK FOREIGN KEY(CategoryId) REFERENCES Categories(CategoryId) ON DELETE CASCADE ON UPDATE CASCADE,
	);
END

IF NOT EXISTS
(SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Favorites')
BEGIN
	CREATE TABLE Favorites (
		UserId INT,
		ProductId INT,
		CONSTRAINT FAVORITES_PK PRIMARY KEY(UserId, ProductId),
		CONSTRAINT PRODUCTS_FK1 FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE ON UPDATE CASCADE,
		CONSTRAINT PRODUCTS_FK2 FOREIGN KEY(ProductId) REFERENCES Products(ProductId) ON DELETE CASCADE ON UPDATE CASCADE,
	);
END

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Favorites;